/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from "@tanstack/react-router";

// Import Routes

import { Route as rootRoute } from "./routes/__root";

// Create Virtual Routes

const IndexLazyImport = createFileRoute("/")();
const QuestsIndexLazyImport = createFileRoute("/quests/")();
const LoginIndexLazyImport = createFileRoute("/login/")();

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: "/",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/index.lazy").then((d) => d.Route));

const QuestsIndexLazyRoute = QuestsIndexLazyImport.update({
  path: "/quests/",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/quests/index.lazy").then((d) => d.Route));

const LoginIndexLazyRoute = LoginIndexLazyImport.update({
  path: "/login/",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/login/index.lazy").then((d) => d.Route));

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      preLoaderRoute: typeof IndexLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/login/": {
      preLoaderRoute: typeof LoginIndexLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/quests/": {
      preLoaderRoute: typeof QuestsIndexLazyImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([IndexLazyRoute, LoginIndexLazyRoute, QuestsIndexLazyRoute]);

/* prettier-ignore-end */
