/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from "@tanstack/react-router";

// Import Routes

import { Route as rootRoute } from "./routes/__root";

// Create Virtual Routes

const IndexLazyImport = createFileRoute("/")();
const QuestsIndexLazyImport = createFileRoute("/quests/")();
const LoginIndexLazyImport = createFileRoute("/login/")();
const QuestsProfileIndexLazyImport = createFileRoute("/quests/profile/")();
const QuestsManageIndexLazyImport = createFileRoute("/quests/manage/")();
const QuestsAnalyticsIndexLazyImport = createFileRoute("/quests/analytics/")();
const QuestsProfileBadgesIndexLazyImport = createFileRoute("/quests/profile/badges/")();
const QuestsManageTagsIndexLazyImport = createFileRoute("/quests/manage/tags/")();
const QuestsManageNewIndexLazyImport = createFileRoute("/quests/manage/new/")();
const QuestsManageEditIndexLazyImport = createFileRoute("/quests/manage/edit/")();

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: "/",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/index.lazy").then((d) => d.Route));

const QuestsIndexLazyRoute = QuestsIndexLazyImport.update({
  path: "/quests/",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/quests/index.lazy").then((d) => d.Route));

const LoginIndexLazyRoute = LoginIndexLazyImport.update({
  path: "/login/",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/login/index.lazy").then((d) => d.Route));

const QuestsProfileIndexLazyRoute = QuestsProfileIndexLazyImport.update({
  path: "/quests/profile/",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/quests/profile/index.lazy").then((d) => d.Route));

const QuestsManageIndexLazyRoute = QuestsManageIndexLazyImport.update({
  path: "/quests/manage/",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/quests/manage/index.lazy").then((d) => d.Route));

const QuestsAnalyticsIndexLazyRoute = QuestsAnalyticsIndexLazyImport.update({
  path: "/quests/analytics/",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/quests/analytics/index.lazy").then((d) => d.Route));

const QuestsProfileBadgesIndexLazyRoute = QuestsProfileBadgesIndexLazyImport.update({
  path: "/quests/profile/badges/",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/quests/profile/badges/index.lazy").then((d) => d.Route));

const QuestsManageTagsIndexLazyRoute = QuestsManageTagsIndexLazyImport.update({
  path: "/quests/manage/tags/",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/quests/manage/tags/index.lazy").then((d) => d.Route));

const QuestsManageNewIndexLazyRoute = QuestsManageNewIndexLazyImport.update({
  path: "/quests/manage/new/",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/quests/manage/new/index.lazy").then((d) => d.Route));

const QuestsManageEditIndexLazyRoute = QuestsManageEditIndexLazyImport.update({
  path: "/quests/manage/edit/",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/quests/manage/edit/index.lazy").then((d) => d.Route));

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      preLoaderRoute: typeof IndexLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/login/": {
      preLoaderRoute: typeof LoginIndexLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/quests/": {
      preLoaderRoute: typeof QuestsIndexLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/quests/analytics/": {
      preLoaderRoute: typeof QuestsAnalyticsIndexLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/quests/manage/": {
      preLoaderRoute: typeof QuestsManageIndexLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/quests/profile/": {
      preLoaderRoute: typeof QuestsProfileIndexLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/quests/manage/edit/": {
      preLoaderRoute: typeof QuestsManageEditIndexLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/quests/manage/new/": {
      preLoaderRoute: typeof QuestsManageNewIndexLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/quests/manage/tags/": {
      preLoaderRoute: typeof QuestsManageTagsIndexLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/quests/profile/badges/": {
      preLoaderRoute: typeof QuestsProfileBadgesIndexLazyImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  LoginIndexLazyRoute,
  QuestsIndexLazyRoute,
  QuestsAnalyticsIndexLazyRoute,
  QuestsManageIndexLazyRoute,
  QuestsProfileIndexLazyRoute,
  QuestsManageEditIndexLazyRoute,
  QuestsManageNewIndexLazyRoute,
  QuestsManageTagsIndexLazyRoute,
  QuestsProfileBadgesIndexLazyRoute,
]);

/* prettier-ignore-end */
