name: rhythmate-web-ci

on:
  push:

env:
  PNPM_VERSION: 9.6.0

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Run Format Check
        run: pnpm run format

      - name: Run Lint Check
        run: pnpm run lint
